# $MirOS: src/bin/ed/USD.doc/09.edtut/Makefile,v 1.2 2005/03/06 18:55:20 tg Exp $
# $OpenBSD: Makefile,v 1.2 2004/02/01 15:21:55 jmc Exp $

DIR=	usd/09.edtut
SRCS=	e.mac e0 e1 e2 e3 e4 e5 e6 e7
MACROS= -ms

.include <bsd.doc.mk>
